export const ui = {
  colors: {
    background: '#F6F8FC',
    surface: '#FFFFFF',
    primary: '#2563EB',
    primaryDark: '#1D4ED8',
    primarySoft: '#EAF1FF',
    text: '#10213D',
    mutedText: '#71809A',
    border: '#E6EBF3',
    danger: '#E5484D',
    dangerSoft: '#FFF0F2',
    success: '#12A66A',
    successSoft: '#EAF9F2',
    warning: '#F59E0B',
    warningSoft: '#FFF6DF',
    disabled: '#A9B5C8',
    disabledSoft: '#F0F3F8',
    overlay: 'rgba(16, 33, 61, 0.42)',
  },
  radius: {
    card: 18,
    button: 16,
    small: 10,
  },
  shadow: {
    shadowColor: '#1D4ED8',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 3,
  },
  subtleShadow: {
    shadowColor: '#10213D',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 2,
  },
} as const;
